name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build backend Docker image
        run: |
          docker build \
            --no-cache \
            -t insite-backend:ci \
            ./back-end
            